In [ ]:
import numpy as np

In [ ]:
 #creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,2.5) #fill array with 10 2.5 elements

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])#list to array
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[2] #accessing array

3

In [ ]:
np.arange(3,
          10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Multi-dimentional arrays

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
n= np.zeros((2,5))
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n[0,1] 

0.0

In [ ]:
#randomly generated arrays
np.random.seed(2)#get the same random numbers by setting the seed
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [ ]:
np.random.seed(2)#get the same random numbers by setting the seed
np.random.randint(low=0, high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [ ]:
#element-wise operations
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a * 5

array([ 0,  5, 10, 15, 20])

In [ ]:
#comparison operations
b= np.arange(5)*10
b

array([ 0, 10, 20, 30, 40])

In [ ]:
a>b

array([False, False, False, False, False])

In [ ]:
a<b

array([False,  True,  True,  True,  True])

In [ ]:
a[a<b]

array([1, 2, 3, 4])

In [ ]:
#summarizing operations
a.min()

0

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.0

In [ ]:
a.std()

1.4142135623730951

##Linear Algebra


*   Vector operations
*   Multiplication
*   Matrix inverse



###Vector operation

In [ ]:
u = np.array([2,4,6,8])
u

array([2, 4, 6, 8])

In [ ]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

###Vector-vector multiplication(dot product)

In [ ]:
u.shape[0]


4

In [ ]:
v.shape[0]

4

In [ ]:
#
def vector_vector_multiplication(u,v):
  assert u.shape[0] == v.shape[0]
  n = u.shape[0]
  result = 0.0
  for i in range(n) :
    result = result + u[i] * v[i]
  return result



In [ ]:
vector_vector_multiplication(u,v)

18.0

In [ ]:
u.dot(v)

18

###Matrix-vector multiplication

In [ ]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
    ])

In [ ]:
v = np.array([
    1,0.5,2,1
])

In [ ]:
def matrix_vector_multiplication(U,v):
  assert U.shape[1] ==v.shape[0]

  num_rows = U.shape[0]
  result = np.zeros(num_rows)

  for i in range(num_rows):
    result[i] = vector_vector_multiplication(U[i],v) 
  return result


In [ ]:
matrix_vector_multiplication(U,v)

array([20. ,  6. ,  8.5])

In [ ]:
U.dot(v)

array([20. ,  6. ,  8.5])

###Matrix-matrix multiplication

#Pandas

In [ ]:
import pandas as pd

In [ ]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [ ]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [ ]:
df[['Make', 'Model', 'MSRP']]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [ ]:
df['id'] = [1,2,3,4,5]

In [ ]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [ ]:
del df['id']

In [ ]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [ ]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [ ]:
df.loc[[1,2,3]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   
3      GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450

In [ ]:
#filtering

df[df['Year'] >=2015]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450  
4        Pickup  32340

In [ ]:
df[
    (df['Year'] >=2015) & (df['Make']== 'Nissan')
   ]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
4        Pickup  32340

In [ ]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [ ]:
df['Vehicle_Style']=df['Vehicle_Style'].str.replace(' ', '_').str.lower()

In [ ]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [ ]:
#summarizing operators
df.MSRP.mean()

30186.0

In [ ]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [ ]:
df.nunique()#get number of unique values

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [ ]:
#missing values
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [ ]:
#grouping, compute avarage price per transmission type
'''
SELECT
    transmission_type
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type
'''

'\nSELECT\n    transmission_type\n    AVG(MSRP)\nFROM\n    cars\nGROUP BY\n    transmission_type\n'

In [ ]:
df.groupby('Transmission Type').MSRP.mean().round(2)

Transmission Type
AUTOMATIC    30800.00
MANUAL       29776.67
Name: MSRP, dtype: float64

In [ ]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]